
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'out/**'
      - '.vscode/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'out/**'
    schedule:
      - cron: '0 0 * * *'
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN_ACTIONS }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: python3 symbol_bn.py
    - name: Upload out file
      run: |
        git config --global user.name "bailiang9966"
        git config --global user.email "bailiang9966@gmail.com"
        git add out/
        git commit -m "Update  on `date +'%Y-%m-%d %H:%M:%S'`"
        git push 
